"""支付渠道、币种与金额单位常量。

支付 provider、配置表校验和回调入口共用这里的定义，避免同一渠道编码散落多处。
"""

from app.utils.money import NORMALIZED_AMOUNT_FACTOR

DISPLAY_PRICE_CHANNEL_CODE = "display"
PAYPAL_PAYMENT_METHOD = "paypal"
PAYPAL_CURRENCY = "USD"
PAYPAL_USD_AMOUNT_UNIT = NORMALIZED_AMOUNT_FACTOR // 100
TELEGRAM_STARS_PAYMENT_METHOD = "telegram_stars"
TELEGRAM_STARS_CURRENCY = "XTR"
TELEGRAM_STARS_AMOUNT_UNIT = NORMALIZED_AMOUNT_FACTOR
